wandb_version: 1

seed:
  desc: null
  value: '42'
in_vocab:
  desc: null
  value: '5_000'
out_vocab:
  desc: null
  value: '5_000'
in_seq_len:
  desc: null
  value: '64'
out_seq_len:
  desc: null
  value: '64'
batch_size:
  desc: null
  value: '32'
num_heads:
  desc: null
  value: '8'
d_model:
  desc: null
  value: '256'
d_ff:
  desc: null
  value: '1024'
enc_layers:
  desc: null
  value: '3'
dec_layers:
  desc: null
  value: '3'
epochs:
  desc: null
  value: 10
dataset:
  desc: null
  value: en_fr
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1703665660.896725
    t:
      1:
      - 12
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
