# This file only serves as a template for executing scripts. 
# You can change the values of the parameters as you want.

path: data/mlm

model: bpe
sample_size: 1_000_000
task: seq2seq
norm_rule: nmt_nfkc # One of [nmt_nfkc, nmt_nfkc_cf, nfkc_cf, nfkc, identity]
shuffle: True
  
seq2seq: 
  src: en
  tgt: fr
  src_vocab: 5_000
  tgt_vocab: 5_000

mlm:
  path: wikipedia.txt
  cls_token: <cls>
  sep_token: <sep>
  vocab_size: 5_000
  
