# This file only serves as a template when execute any scripts. 
# You can change the values of the parameters as you want.

seed: 42

model:
  in_vocab: 5_000
  out_vocab: 5_000
  emb_dim: 256
  num_heads: 8
  num_layers: 3
  mlp_dim: 1024
  qkv_dim: 256
  max_len: 64
  dropout: 0.1
  deterministic: False
  decode: False

training:
  task: translation
  dataset: europarl
  lang_pair: en_fr
  epochs: 10
  batch_size: 32
  path: data/translation/europarl/en_fr
  src: en
  src_max_len: 64
  tgt: fr
  tgt_max_len: 64
  cache_dir: cache/translation/europarl/en_fr

tokenizer:
  path: tokenizer/translation/europarl/en_fr
  use_separate_tokenizer: True
  src_lang: en
  tgt_lang: fr
  lang: null
  alpha: 0.1

optimizer:
  lr: 0.001
  warmup_steps: 4000
  peak_lr: 0.001
  decay_steps: 8000
  final_lr: 0.0001
  
wandb:
  use_wandb: False
  project: transformer_europarl_en_fr
  notes: Baseline transformer model
  name: Initial run
  run_config:
    task: translation
    dataset: europarl
    lang_pair: en_fr


checkpoint:
  use_checkpoint: True
  overwrite: True
  path: checkpoint/translation/europarl/en_fr/transformer
  freq: 25
  max_to_keep: 5